# Generated by Django 5.1.2 on 2024-10-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=25)),
                ('photo', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('content', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
