# Generated by Django 5.1.2 on 2024-10-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_post_caption_post_comments_post_likes_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
