# Generated by Django 5.1.2 on 2024-10-25 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_post_caption_post_comments_post_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
