# Generated by Django 5.1.2 on 2024-10-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='search',
            new_name='searches',
        ),
    ]
