# Generated by Django 5.1.2 on 2024-10-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_rename_search_search_searches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='searches',
        ),
        migrations.AddField(
            model_name='search',
            name='item',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
